services:
  ujian:
    container_name: ujian
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '10001:8080'
    restart: 'no'
    labels:
      uid: "2206082556"
    networks:
      - backend-network
    environment:
      - DATABASE_URL_DEV=jdbc:postgresql://db:5432/ujian
      - DEV_USERNAME=postgres
      - DEV_PASSWORD=secret99
      - JWT_SECRET_KEY=jwt-secret-key
networks:
  backend-network:
    name: apap-083_backend-network
    external: true